[tool.poetry]
name = "crawler"
version = "0.1.0"
description = ""
authors = ["D3lux3 <dani.haapaniemi@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
